version: '3.8'

services:
  web:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: ./php